### ISSUE TITLE
Failed with invalid token on GovCloud

### ISSUE THREAD

**Issue by barryku** [adamsb6/s3_file#82]
Is there a way to give a region as parameter?  GovCloud without region yields invalid token error for some reason.  It works fine after I hard-coded region as 'us-gov-west-1' at do_request in s3_file.rb.

**Comment by joekiller** [comment]
Take the bucket out and use the parameter s3_url - Custom S3 URL. If
specified this URL *must* include the bucket name at the end. (optional) ie
https://s3.amazonaws.com/bucket

Find your URL here:
http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html

Is there a way to give a region as parameter? GovCloud without region
yields invalid token error for some reason. It works fine after I
hard-coded region as 'us-gov-west-1' at do_request in s3_file.rb.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adamsb6/s3_file/issues/82>, or mute the thread
<https://github.com/notifications/unsubscribe/AA-bx5rh9_6gtC9B8cJBq8GVMuAHrQaaks5qJ3qQgaJpZM4IxlIp>
.

**Comment by barryku** [comment]
@joekiller, works perfectly.  Thank you.
